# Generated by Django 5.1.4 on 2024-12-13 19:00

import ckeditor.fields
import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
                ('text', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField(null=True)),
                ('text_uz', ckeditor.fields.RichTextField(null=True)),
                ('philosophy', ckeditor.fields.RichTextField()),
                ('philosophy_ru', ckeditor.fields.RichTextField(null=True)),
                ('philosophy_uz', ckeditor.fields.RichTextField(null=True)),
                ('philosophy_image', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
                ('mission', ckeditor.fields.RichTextField()),
                ('mission_ru', ckeditor.fields.RichTextField(null=True)),
                ('mission_uz', ckeditor.fields.RichTextField(null=True)),
                ('mission_image', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
                ('title', models.TextField()),
                ('title_ru', models.TextField(null=True)),
                ('title_uz', models.TextField(null=True)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('address_ru', models.CharField(max_length=100, null=True)),
                ('address_uz', models.CharField(max_length=100, null=True)),
                ('address_link', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('iframe_src', models.CharField(max_length=500)),
                ('working_time', models.CharField(max_length=100)),
                ('working_time_ru', models.CharField(max_length=100, null=True)),
                ('working_time_uz', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('phone2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_ru', models.CharField(max_length=300, null=True)),
                ('title_uz', models.CharField(max_length=300, null=True)),
                ('icon', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
                ('icon', models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator])),
            ],
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='main.application')),
            ],
        ),
    ]
